package org.uevola.jsonautovalidation.runtime.generator

import io.github.oshai.kotlinlogging.KotlinLogging
import org.springframework.beans.factory.support.BeanDefinitionBuilder
import org.springframework.beans.factory.support.BeanDefinitionRegistry
import org.uevola.jsonautovalidation.aot.utils.ClassPathUtils
import org.uevola.jsonautovalidation.common.extensions.getMethodsToValidate
import org.uevola.jsonautovalidation.common.extensions.getParamsToValidate
import org.uevola.jsonautovalidation.common.extensions.isIgnoredType
import org.uevola.jsonautovalidation.runtime.common.strategies.validators.JsonSchemaValidatorBase
import kotlin.time.Duration
import kotlin.time.measureTime

internal object ValidatorBeansGenerator {
    private class RuntimeDtoValidator(dtoClass: Class<*>) : JsonSchemaValidatorBase(dtoClass)

    private val logger = KotlinLogging.logger {}

    private var nbAutoGeneratedBeans = 0
    private val generatedDtoValidators = mutableSetOf<String>()

    fun generateDtoValidator(registry: BeanDefinitionRegistry) {
        logger.info { "Generation of Json Validator Beans (runtime mode)..." }
        val elapsed: Duration = measureTime {
            ClassPathUtils.getControllersToValidate().forEach { controller ->
                controller.getMethodsToValidate().forEach { method ->
                    method.getParamsToValidate(controller)
                        .forEach { parameter ->
                            registerGenericDtoValidator(parameter.type, registry)
                        }
                }
            }
        }
        logger.info { "Generation of Json Validator Beans (runtime) completed in ${elapsed.inWholeMilliseconds}ms" }
    }

    private fun registerGenericDtoValidator(dtoClass: Class<*>, registry: BeanDefinitionRegistry) {
        if (dtoClass.isIgnoredType()) return
        if (generatedDtoValidators.contains(dtoClass.simpleName)) return

        val beanName = "${dtoClass.simpleName}GeneratedValidator"

        val beanDefinition = BeanDefinitionBuilder
            .genericBeanDefinition(JsonSchemaValidatorBase::class.java) {
                RuntimeDtoValidator(dtoClass)
            }
            .beanDefinition

        registry.registerBeanDefinition(beanName, beanDefinition)
        generatedDtoValidators.add(dtoClass.simpleName)
        nbAutoGeneratedBeans += 1
    }
}