package org.uevola.jsonautovalidation.aot.generators

import com.squareup.javapoet.JavaFile
import com.squareup.javapoet.MethodSpec
import com.squareup.javapoet.TypeSpec
import io.github.oshai.kotlinlogging.KotlinLogging
import org.springframework.aot.generate.GenerationContext
import org.springframework.stereotype.Component
import org.uevola.jsonautovalidation.aot.utils.ClassPathUtils.getControllersToValidate
import org.uevola.jsonautovalidation.common.Constants.VALIDATORS_PACKAGE_NAME
import org.uevola.jsonautovalidation.common.extensions.getMethodsToValidate
import org.uevola.jsonautovalidation.common.extensions.getParamsToValidate
import org.uevola.jsonautovalidation.common.extensions.isIgnoredType
import org.uevola.jsonautovalidation.runtime.strategies.validators.JsonSchemaValidator
import javax.lang.model.element.Modifier
import kotlin.time.Duration
import kotlin.time.measureTime

internal object ValidatorBeansGenerator {
    private val logger = KotlinLogging.logger {}

    private var nbAutoGeneratedBeans = 0
    private val generatedDtoValidators = mutableSetOf<String>()

    fun generateDtoValidator(context: GenerationContext) {
        logger.info { "Generation of Json Validator Bean..." }
        val elapsed: Duration = measureTime {
            getControllersToValidate().forEach { controller ->
                controller.getMethodsToValidate().forEach { method ->
                    method.getParamsToValidate(controller)
                        .forEach { parameter -> generateDtoValidator(parameter.type, context) }
                }
            }
        }
        logger.info { "Generation of Json Validator Beans completed in ${elapsed.inWholeMilliseconds}ms" }
        logger.info { "Number of Json Validator Bean generated: $nbAutoGeneratedBeans" }
    }

    private fun generateDtoValidator(dtoClass: Class<*>, context: GenerationContext) {
        if (dtoClass.isIgnoredType()) return
        if (generatedDtoValidators.contains(dtoClass.simpleName))
            return
        val validatorClassName = "${dtoClass.simpleName}GeneratedValidator"

        logger.debug { "Creation of validator class $validatorClassName in package $VALIDATORS_PACKAGE_NAME" }

        val validatorClass = validatorClass(validatorClassName, dtoClass)
        val javaFile = JavaFile.builder(VALIDATORS_PACKAGE_NAME, validatorClass)
            .build()
        context.generatedFiles.addSourceFile("${VALIDATORS_PACKAGE_NAME}.$validatorClassName") { writer ->
            writer.append(javaFile.toString())
        }
        generatedDtoValidators.add(dtoClass.simpleName)
        nbAutoGeneratedBeans += 1
    }

    private fun validatorClass(
            validatorClassName: String,
            dtoClass: Class<*>
        ) = TypeSpec.classBuilder(validatorClassName)
        .addModifiers(Modifier.PUBLIC)
        .superclass(JsonSchemaValidator::class.java)
        .addAnnotation(Component::class.java)
        .addMethod(
            MethodSpec.constructorBuilder()
                .addModifiers(Modifier.PUBLIC)
                .addStatement($$"super($T.class)", dtoClass)
                .build()
        )
        .build()

}